"""init

Revision ID: 8f9f9a098c1c
Revises: 
Create Date: 2022-07-22 23:12:00.599718

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f9f9a098c1c"
down_revision = None  # type:ignore
branch_labels = None  # type:ignore
depends_on = None  # type:ignore


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offer",
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("items_in_stock", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offer")
    op.drop_table("product")
    # ### end Alembic commands ###
